### ISSUE TITLE
Consider changing "answer to React" to "alternative to virtual DOM"

### ISSUE THREAD

**Issue by lettertwo** [bryhoyt/emerj#3]
I wrote more about why I think you should consider this on [HN] (shudder). Just for the sake of conversation, I'll reproduce that comment here:
> This is a clever lib, nicely done! I'm writing in to say that I think your presentation of it could benefit from some focused revision.
>
>In positioning something as an "answer to React", I think it's important to note what React's goals are. The React site (https://reactjs.org) describes itself as a declarative, component-based library for building UI that you can "learn once and write everywhere". The crucial thing to note here is that efficient updates to the DOM are explicitly not a core justification for React.
>
>In fact, React's virtual DOM is often described by React developers as an implementation detail, not as a reason for React's existence and adoption. The appeal of React is in its declarative composition model for building UI, which frees developers from tedious data-bound state management on the DOM and beyond (react-dom, react-native, react-vr, etc.).
>
>I believe this lib is better positioned as an alternative to so-called 'virtual DOM' implementations, rather than as an answer to React, since it provides no answer to core React features (declarative, composable components that can target all kinds of platforms). 

[HN]: https://news.ycombinator.com/item?id=15799065

**Comment by bryhoyt** [comment]
Thanks, fair call. Sorry, took a little while to respond to this one as I've been out of town.

I've addressed this to some extent in https://github.com/bryhoyt/emerj/commit/7a741165ccc45c6b941b9206043a4339fa2c2a0c

I don't 100% agree with the React folks that the virtual DOM is exactly an implementation detail. Yes, techincally perhaps it is, but IMO it's the single most important implementation detail if you happen to be using React for the purpose of building data-driven HTML UIs. Which for me would be almost the only reason to use React. But not necessarily for others, so I take your point.

**Comment by lettertwo** [comment]
👍 I appreciate your willingness to consider my little screed. As i said, this is nice work; thanks for sharing it!
