### ISSUE TITLE
NPM Release

### ISSUE THREAD

**Issue by chocolateboy** [bryhoyt/emerj#4]
Can you release this as an NPM package? I can raise a PR if you're not sure how to do this.

**Comment by bryhoyt** [comment]
Sounds awesome, thanks. Yes, I would love to see a PR as a starting point.

**Comment by bryhoyt** [comment]
I've published this now. Thanks so much for the excellent PR, @chocolateboy -- I haven't published an npm module before so it was extremely helpful to have some of the tricky bits taken care of for me!

Available at https://www.npmjs.com/package/emerj

Release tagged as 1.0.0 in git.

**Comment by chocolateboy** [comment]
Thanks! :tada:
